
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-${KUBE_NAMESPACE}
  labels: 
    app: ${KUBE_NAMESPACE}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs-storage/${KUBE_NAMESPACE}
    server: k8s-nfs-server.bgslcdevops.test
