
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-${APP_NAME}
  labels: 
    app: ${APP_NAME}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs-storage/${APP_NAME}
    server: k8s-nfs-server.bgslcdevops.test
