---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-${APP_NAME}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: ${APP_NAME}

