---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-${KUBE_NAMESPACE}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: ${KUBE_NAMESPACE}

