# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 80
    url: http://pygeoapi-2018-main.kube-idev.bgslcdevops.test/
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    # cors: true
    pretty_print: true
    limit: 10
    templates:
        path: /pygeoapi/bgs-skin-dashboard/templates
        static: /pygeoapi/bgs-skin-dashboard/static # css/js/img
    map:
        url: https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}.png
        attribution: '<a href="https://www.esri.com/en-us/home">ESRI</a> | Map data &copy; <a href="https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer">ArcGIS</a>'
    # ogc_schemas_location: /opt/schemas.opengis.net

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: British Geological Survey - OGCAPI Server
        description: This server provides OGCAPI endpoints for a selection of BGS OpenGeoscience geospatial data. The BGS has a wide range of datasets and wants to increase access to these, publishing as many as possible as OpenGeoscience under Open Government Licence. 
        keywords:
            - geospatial
            - data
            - api
            - ogc
            - geology
        keywords_type: theme
        terms_of_service:  https://www.bgs.ac.uk/legal-and-policy/terms-of-use/
        url: https://bgs.ac.uk
    license:
        name: Open Government Licence
        url: http://reference.data.gov.uk/id/open-government-licence
    provider:
        name: British Geological Survey
        url: https://bgs.ac.uk
    contact:
        name: Lewis, Edward
        position: Standards Lead
        address: British Geological Survey
        city: Keyworth
        stateorprovince: Nottinghamshire
        postalcode: NG12 5GG
        country: UK
        phone:  +44 115 936 3143
        fax: +44 115 936 3276
        email:  enquiries@bgs.ac.uk
        url: enquiries@bgs.ac.uk
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    BGSGeology50kBedrock:
        type: collection
        title: BGS Geology 50k Bedrock
        description: Generalised digital geological map data based on BGS’s New Series 1:50 000 and 1:63 360-scale (one-inch to one-mile) maps with updated nomenclature, including a few 1:100 000-scale maps of Orkney and the Hebrides. Many BGS geology maps are now available digitally. The Digital Geological Map of Great Britain project (formerly known as DiGMapGB) has prepared 1:625 000, 1:250 000, 1:50 000 and 1:10 000-scale datasets for England, Wales and Scotland. Work continues to upgrade these. 
        keywords:
            - geology
            - britain
#        context:
#            - schema: http://data.bgs.ac.uk/ref/Lexicon
#              LEX: schema:notation
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.bgs.ac.uk/datasets/bgs-geology-50k-digmapgb/
              hreflang: en-UK
            - type: text/html
              rel: canonical
              title: User Guide
              href: https://www.bgs.ac.uk/?wpdmdl=13665
              hreflang: en-UK
        extents:
            spatial:
                bbox: [-8,49.9,2,61]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11
                end: null  # or empty (either means open ended)
        providers:
            - type: tile
              name: MVT
              data: /pygeoapi/bgsdata/gb_50k_bedrock/  # local directory tree
            # data: https://example.org/ne_110m_lakes/{z}/{x}/{y}.pbf
              options:
                  metadata_format: tilejson # default | tilejson
                  bounds: [-7.733181,49.863063,1.763249,60.860926]
                  zoom:
                      min: 9
                      max: 13
                  schemes:
                      - WebMercatorQuad
                      - WorldCRS84Quad
              format:
                    name: pbf
                    mimetype: application/vnd.mapbox-vector-tile

    BGSGeology625kBedrock:
        type: collection
        title: BGS Geology 625k Bedrock
        description: Bedrock features of the generalised digital geological map data based on BGS's published poster maps of the UK (North and South). Bedrock related themes created by generalisation of 1:50 000 data to make the 2007 fifth edition Bedrock Geology map. 
        keywords:
            - geology
            - britain
#        context:
#            - schema: http://data.bgs.ac.uk/ref/Lexicon
#              LEX: schema:notation
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.bgs.ac.uk/products/digitalmaps/DiGMapGB_625.html
              hreflang: en-UK
        extents:
            spatial:
                bbox: [-9,49.5,3,61]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11
                end: null  # or empty (either means open ended)
        providers:
            - type: feature
              name: SQLiteGPKG
              data: /pygeoapi/bgsdata/bgsgeology625k.gpkg
              id_field: fid
              table: bedrock_geology
            - type: tile
              name: MVT
              data: /pygeoapi/tests/data/tiles/gb_625k_bedrock/  # local directory tree
            # data: https://example.org/ne_110m_lakes/{z}/{x}/{y}.pbf
              options:
                  metadata_format: tilejson # default | tilejson
                  bounds: [[-7.733181,49.863063],[1.763249,60.860926]]
                  zoom:
                      min: 6
                      max: 10
                  schemes:
                      - WebMercatorQuad
                      - WorldCRS84Quad
              format:
                    name: pbf
                    mimetype: application/vnd.mapbox-vector-tile

    BGSGeology625kDykes:
        type: collection
        title: BGS Geology 625k Dykes
        description: Dyke features of the generalised digital geological map data based on BGS's published poster maps of the UK (North and South). Bedrock related themes created by generalisation of 1:50 000 data to make the 2007 fifth edition Bedrock Geology map. 
        keywords:
            - geology
            - britain
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.bgs.ac.uk/products/digitalmaps/DiGMapGB_625.html
              hreflang: en-UK
        extents:
            spatial:
                bbox: [-9,49.5,3,61]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11
                end: null  # or empty (either means open ended)
        providers:
            - type: feature
              name: SQLiteGPKG
              data: /pygeoapi/bgsdata/bgsgeology625k.gpkg
              id_field: fid
              table: dykes_geology       

    BGSGeology625kFaults:
        type: collection
        title: BGS Geology 625k Faults
        description: Fault features of the generalised digital geological map data based on BGS's published poster maps of the UK (North and South). Bedrock related themes created by generalisation of 1:50 000 data to make the 2007 fifth edition Bedrock Geology map. 
        keywords:
            - geology
            - britain
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.bgs.ac.uk/products/digitalmaps/DiGMapGB_625.html
              hreflang: en-UK
        extents:
            spatial:
                bbox: [-9,49.5,3,61]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11
                end: null  # or empty (either means open ended)
        providers:
            - type: feature
              name: SQLiteGPKG
              data: /pygeoapi/bgsdata/bgsgeology625k.gpkg
              id_field: fid
              table: fault_geology

    BGSGeology625kSuperficial:
        type: collection
        title: BGS Geology 625k Superficial
        description: Superficial features of the generalised digital geological map data based on BGS's published poster maps of the UK (North and South). Bedrock related themes created by generalisation of 1:50 000 data to make the 2007 fifth edition Bedrock Geology map. 
        keywords:
            - geology
            - britain
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.bgs.ac.uk/products/digitalmaps/DiGMapGB_625.html
              hreflang: en-UK
        extents:
            spatial:
                bbox: [-9,49.5,3,61]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11
                end: null  # or empty (either means open ended)
        providers:
            - type: feature
              name: SQLiteGPKG
              data: /pygeoapi/bgsdata/bgsgeology625k.gpkg
              id_field: fid
              table: superficial_geology 

