# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 80
    url: http://osgeodev.bgs.ac.uk/pygeoapi
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    # cors: true
    pretty_print: true
    limit: 10
    map:
        url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
        attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    # ogc_schemas_location: /opt/schemas.opengis.net

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: BGS Instance of pygeoapi
        description: pygeoapi provides an API to geospatial data
        keywords:
            - geospatial
            - data
            - api
            - geology
        keywords_type: theme
        terms_of_service: http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
        url: https://bgs.ac.uk
    license:
        name: Open Government Licence
        url: http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
    provider:
        name: British Geological Survey
        url: https://bgs.ac.uk
    contact:
        name: Lewis, Edward
        position: Standards Lead
        address: British Geological Survey
        city: Keyworth
        stateorprovince: Nottinghamshire
        postalcode: NG12 5GG
        country: UK
        phone:  +44 115 936 3143
        fax: +44 115 936 3276
        email:  enquiries@bgs.ac.uk
        url: enquiries@bgs.ac.uk
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    BGSGeology625kBedrock:
        type: collection
        title: BGS Geology 625k Bedrock
        description: Generalised digital geological map data based on BGS's published poster maps of the UK (North and South). Bedrock related themes created by generalisation of 1:50 000 data to make the 2007 fifth edition Bedrock Geology map. 
        keywords:
            - geology
            - britain
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.bgs.ac.uk/products/digitalmaps/DiGMapGB_625.html
              hreflang: en-UK
        extents:
            spatial:
                bbox: [-9,49.5,3,61]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11
                end: null  # or empty (either means open ended)
        providers:
            - type: feature
              name: GeoJSON
              data: tests/data/bedrock_geology.geojson
              id_field: fid    

    BGSGeology625kDykes:
        type: collection
        title: BGS Geology 625k Dykes
        description: Generalised digital geological map data based on BGS's published poster maps of the UK (North and South). Bedrock related themes created by generalisation of 1:50 000 data to make the 2007 fifth edition Bedrock Geology map. 
        keywords:
            - geology
            - britain
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.bgs.ac.uk/products/digitalmaps/DiGMapGB_625.html
              hreflang: en-UK
        extents:
            spatial:
                bbox: [-9,49.5,3,61]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11
                end: null  # or empty (either means open ended)
        providers:
            - type: feature
              name: GeoJSON
              data: tests/data/dykes_geology.geojson
              id_field: fid   

    BGSGeology625kFaults:
        type: collection
        title: BGS Geology 625k Faults
        description: Generalised digital geological map data based on BGS's published poster maps of the UK (North and South). Bedrock related themes created by generalisation of 1:50 000 data to make the 2007 fifth edition Bedrock Geology map. 
        keywords:
            - geology
            - britain
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.bgs.ac.uk/products/digitalmaps/DiGMapGB_625.html
              hreflang: en-UK
        extents:
            spatial:
                bbox: [-9,49.5,3,61]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11
                end: null  # or empty (either means open ended)
        providers:
            - type: feature
              name: GeoJSON
              data: tests/data/fault_geology.geojson
              id_field: fid    

    BGSGeology625kSuperficial:
        type: collection
        title: BGS Geology 625k Superficial
        description: Generalised digital geological map data based on BGS's published poster maps of the UK (North and South). Bedrock related themes created by generalisation of 1:50 000 data to make the 2007 fifth edition Bedrock Geology map. 
        keywords:
            - geology
            - britain
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.bgs.ac.uk/products/digitalmaps/DiGMapGB_625.html
              hreflang: en-UK
        extents:
            spatial:
                bbox: [-9,49.5,3,61]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11
                end: null  # or empty (either means open ended)
        providers:
            - type: feature
              name: GeoJSON
              data: tests/data/superficial_geology.geojson
              id_field: fid     

    BGSDykes625kSubset:
        type: collection
        title: BGS Geology 625k Dykes ES Subset
        description: Generalised digital geological map data based on BGS's published poster maps of the UK (North and South). Bedrock related themes created by generalisation of 1:50 000 data to make the 2007 fifth edition Bedrock Geology map. 
        keywords:
            - geology
            - britain
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://www.bgs.ac.uk/products/digitalmaps/DiGMapGB_625.html
              hreflang: en-UK
        extents:
            spatial:
                bbox: [-9,49.5,3,61]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11
                end: null  # or empty (either means open ended)
        providers:
            - type: feature
              name: Elasticsearch
              data: http://hwlelastic01.ad.nerc.ac.uk:9200/dykes_subset
              id_field: geonameid
              
