---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-${KUBE_NAMESPACE}
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

